// ============================================================
// Lesson Content Data
// All lesson content lives here as structured, typed data.
// The LessonContent component renders each block by type.
// ============================================================

export type ContentBlock =
  | { type: "paragraph"; text: string }
  | { type: "heading"; text: string; level: 2 | 3 }
  | { type: "command"; command: string; description?: string }
  | { type: "code"; code: string; language?: string; filename?: string }
  | { type: "callout"; variant: "info" | "tip" | "warning" | "meta"; title?: string; text: string }
  | { type: "expandable"; title: string; content: ContentBlock[] }
  | { type: "list"; items: string[]; ordered?: boolean }
  | { type: "checklist"; items: { id: string; label: string; sublabel?: string }[] };

export interface LessonSection {
  id: string;
  title: string;
  content: ContentBlock[];
}

export interface Lesson {
  slug: string;
  number: number;
  title: string;
  subtitle: string;
  estimatedMinutes: number;
  sections: LessonSection[];
}

export const lessons: Lesson[] = [
  // ──────────────────────────────────────────────
  // LESSON 1: Getting Set Up
  // ──────────────────────────────────────────────
  {
    slug: "getting-set-up",
    number: 1,
    title: "Getting Set Up",
    subtitle: "Install the tools that make everything else possible",
    estimatedMinutes: 20,
    sections: [
      {
        id: "terminal",
        title: "Open Your Terminal",
        content: [
          { type: "paragraph", text: "The Terminal lets you talk to your computer by typing instead of clicking. Open it now:" },
          { type: "command", command: "open -a Terminal", description: "Or use Spotlight: Cmd+Space → type 'Terminal' → Enter" },
        ],
      },
      {
        id: "homebrew",
        title: "Install Homebrew",
        content: [
          { type: "paragraph", text: "Homebrew is a package manager — it installs developer tools for you." },
          { type: "command", command: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"` },
          { type: "callout", variant: "warning", text: "It will ask for your Mac password. Nothing appears when you type — that's normal. Just type and hit Enter." },
          { type: "command", command: "brew --version", description: "Verify it worked" },
          { type: "expandable", title: "If 'brew' is not found after install", content: [
            { type: "paragraph", text: "Run the PATH commands that Homebrew printed. Look for lines starting with 'echo' and 'eval' — copy and run them." },
          ]},
        ],
      },
      {
        id: "nodejs",
        title: "Install Node.js",
        content: [
          { type: "paragraph", text: "Node.js runs JavaScript outside the browser. Our tools and framework both need it." },
          { type: "command", command: "brew install node" },
          { type: "command", command: "node --version && npm --version", description: "Both should print version numbers" },
        ],
      },
      {
        id: "git",
        title: "Install Git",
        content: [
          { type: "paragraph", text: "Git tracks changes to your code. More on this later — just install it." },
          { type: "command", command: "brew install git" },
          { type: "command", command: "git --version", description: "Verify" },
          { type: "command", command: `git config --global user.name "Your Name"`, description: "Use your real name" },
          { type: "command", command: `git config --global user.email "your@email.com"`, description: "Use your GitHub email" },
        ],
      },
      {
        id: "github-cli",
        title: "Install GitHub CLI",
        content: [
          { type: "paragraph", text: "Lets you push code to GitHub from the terminal." },
          { type: "command", command: "brew install gh" },
          { type: "command", command: "gh auth login", description: "Follow the prompts: GitHub.com → HTTPS → Login with browser" },
          { type: "command", command: "gh auth status", description: "Should show you're logged in" },
        ],
      },
      {
        id: "claude-code",
        title: "Install Claude Code",
        content: [
          { type: "paragraph", text: "Claude in your terminal — it reads your code, writes files, and builds apps from plain English." },
          { type: "command", command: "curl -fsSL https://claude.ai/install.sh | bash" },
          { type: "command", command: "claude --version", description: "Verify" },
          { type: "paragraph", text: "Run 'claude' in any directory. It prompts you to log in via browser the first time." },
          { type: "callout", variant: "meta", text: "You just installed the tools that built this website. Every page you're reading was generated by Claude Code." },
          { type: "expandable", title: "If the install script fails with permission errors", content: [
            { type: "command", command: "sudo curl -fsSL https://claude.ai/install.sh | bash" },
          ]},
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────
  // LESSON 2: The Big Picture
  // ──────────────────────────────────────────────
  {
    slug: "the-big-picture",
    number: 2,
    title: "The Big Picture",
    subtitle: "See how websites work by inspecting this one",
    estimatedMinutes: 10,
    sections: [
      {
        id: "what-is-vibecoding",
        title: "What is Vibecoding?",
        content: [
          { type: "paragraph", text: "You describe what you want in plain English. AI writes the code. You review, iterate, and ship." },
        ],
      },
      {
        id: "see-for-yourself",
        title: "Try It: Inspect This Page",
        content: [
          { type: "paragraph", text: "A website is just HTML (structure), CSS (design), and JavaScript (interactivity) files. Let's prove it:" },
          { type: "list", ordered: true, items: [
            "Right-click anywhere on this page → select 'Inspect'",
            "Look at the Elements tab — that's the HTML structure of what you're reading",
            "Try hovering over elements in the panel — watch them highlight on the page",
            "Click the Console tab — this is where errors show up",
          ] },
          { type: "callout", variant: "meta", text: "Everything you see in that panel was generated by the code in this project. You'll be looking at that code shortly." },
        ],
      },
      {
        id: "frontend-backend",
        title: "Frontend vs Backend",
        content: [
          { type: "list", items: [
            "Frontend — what the user sees (runs in the browser)",
            "Backend — what happens on the server (databases, authentication, payments)",
          ] },
          { type: "paragraph", text: "We're focused on frontend today. That's where most vibecoded projects start." },
        ],
      },
      {
        id: "local-vs-production",
        title: "Local vs Production",
        content: [
          { type: "list", items: [
            "Local — your site running on your computer (localhost:3000). Only you can see it.",
            "Production — your site on a server, accessible to anyone with the URL.",
          ] },
          { type: "callout", variant: "meta", text: "This site is running in production on Vercel's servers right now. By the end of this session, you'll have deployed here too." },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────
  // LESSON 3: Understanding Your Tools
  // ──────────────────────────────────────────────
  {
    slug: "understanding-your-tools",
    number: 3,
    title: "Understanding Your Tools",
    subtitle: "Learn the difference by using both",
    estimatedMinutes: 10,
    sections: [
      {
        id: "two-claudes",
        title: "Two Claudes",
        content: [
          { type: "list", items: [
            "Claude.ai — for thinking and planning (web chat, good for questions and brainstorming)",
            "Claude Code — for building (terminal tool, reads and edits your files directly)",
          ] },
          { type: "callout", variant: "meta", text: "This entire website was built by typing prompts into Claude Code. Not a single line was typed by hand." },
        ],
      },
      {
        id: "try-claude-ai",
        title: "Try It: Ask Claude.ai a Question",
        content: [
          { type: "list", ordered: true, items: [
            "Open claude.ai in your browser",
            "Ask: 'Explain what Next.js is in 2 sentences'",
            "Now ask: 'What's the difference between a framework and a library?'",
          ] },
          { type: "paragraph", text: "This is where you go to think, plan, and understand. Keep it open during development." },
        ],
      },
      {
        id: "prompting-rules",
        title: "The 4 Rules of Prompting",
        content: [
          { type: "list", ordered: true, items: [
            "Be specific — 'a landing page with my name, bio, and 3 social links as buttons' not 'build me a website'",
            "Feed it errors — copy the ENTIRE error message and paste it in. This is the #1 vibecoding skill.",
            "Small steps — get one thing working, then add the next. Don't ask for the whole app at once.",
            "Start fresh when stuck — if Claude is going in circles, a new conversation with a clearer prompt is faster.",
          ] },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────
  // LESSON 4: Frameworks
  // ──────────────────────────────────────────────
  {
    slug: "frameworks",
    number: 4,
    title: "Frameworks",
    subtitle: "What they are and why we use Next.js",
    estimatedMinutes: 5,
    sections: [
      {
        id: "what-is-a-framework",
        title: "What is a Framework?",
        content: [
          { type: "paragraph", text: "A pre-built structure for your code. It handles routing (URLs → pages), components (reusable UI pieces), and build tools so you don't start from zero." },
        ],
      },
      {
        id: "why-nextjs",
        title: "Why Next.js?",
        content: [
          { type: "list", items: [
            "Most popular React framework — Claude knows it extremely well",
            "Built by Vercel — deploys with zero configuration",
            "File-based routing — create a file, get a URL",
          ] },
          { type: "callout", variant: "meta", title: "Look Around You", text: "This site IS a Next.js app. Open src/app/lessons/[slug]/page.tsx — that single file renders every lesson page you're reading." },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────
  // LESSON 5: Version Control with GitHub
  // ──────────────────────────────────────────────
  {
    slug: "version-control",
    number: 5,
    title: "Version Control with GitHub",
    subtitle: "See it in action before learning the theory",
    estimatedMinutes: 10,
    sections: [
      {
        id: "try-it-first",
        title: "Try It: See Git in Action",
        content: [
          { type: "paragraph", text: "Git tracks every change to your code. GitHub stores it online. Let's see it working:" },
          { type: "command", command: "git log --oneline", description: "Run this in the project directory — you'll see every change that built this site" },
          { type: "command", command: "git diff HEAD~1", description: "See what changed in the most recent commit" },
          { type: "callout", variant: "meta", text: "That history IS the history of this website. Every commit is a snapshot — a save point you can always go back to." },
        ],
      },
      {
        id: "key-concepts",
        title: "4 Words to Know",
        content: [
          { type: "list", items: [
            "Repo — a project folder that Git is tracking",
            "Commit — a save point with a note about what changed",
            "Push — upload your commits to GitHub",
            "Branch — a parallel copy for experimenting (don't worry about this today)",
          ] },
        ],
      },
      {
        id: "why-it-matters",
        title: "Why This Matters",
        content: [
          { type: "paragraph", text: "Every time you push to GitHub, Vercel automatically redeploys your site. That's the whole pipeline: edit → commit → push → live." },
          { type: "callout", variant: "tip", text: "You don't need to memorize git commands. Just tell Claude Code 'commit and push' — it handles the rest." },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────
  // LESSON 6: Let's Build Something
  // ──────────────────────────────────────────────
  {
    slug: "lets-build-something",
    number: 6,
    title: "Let's Build Something",
    subtitle: "The hands-on part — follow along step by step",
    estimatedMinutes: 30,
    sections: [
      {
        id: "scaffold",
        title: "Step 1: Create the Project",
        content: [
          { type: "command", command: "mkdir my-site && cd my-site", description: "Create a project folder" },
          { type: "command", command: "npx create-next-app@latest . --typescript --tailwind --app --src-dir --eslint --use-npm", description: "Scaffold a Next.js app" },
          { type: "callout", variant: "meta", text: "This is exactly how this website started — one command." },
        ],
      },
      {
        id: "start-claude",
        title: "Step 2: Start Claude Code",
        content: [
          { type: "command", command: "claude", description: "Start Claude Code in your project directory" },
        ],
      },
      {
        id: "describe-and-build",
        title: "Step 3: Tell Claude What to Build",
        content: [
          { type: "paragraph", text: "Be specific. Here's an example prompt:" },
          { type: "code", code: `Build me a personal landing page with:
- My name "Alex" in large text at the top
- A short bio: "Designer and builder. I make things for the web."
- Three social links as styled buttons: Twitter, GitHub, LinkedIn
- A dark background with light text
- Clean, modern design with good spacing`, language: "prompt" },
        ],
      },
      {
        id: "run-locally",
        title: "Step 4: See It Running",
        content: [
          { type: "command", command: "npm run dev", description: "Start the dev server" },
          { type: "paragraph", text: "Open localhost:3000 in your browser. That's your site." },
        ],
      },
      {
        id: "iterate",
        title: "Step 5: Change Something",
        content: [
          { type: "paragraph", text: "Ask Claude to modify your site. Try each of these:" },
          { type: "list", ordered: true, items: [
            "'Make the buttons bigger and add hover effects'",
            "'Change the background to a dark gradient'",
            "'Add an emoji next to my name'",
          ] },
          { type: "paragraph", text: "Watch the browser update after each change. This is the iteration loop — the core of vibecoding." },
        ],
      },
      {
        id: "break-and-fix",
        title: "Step 6: Break Something on Purpose",
        content: [
          { type: "paragraph", text: "Tell Claude: 'Delete the closing tag on the main div in page.tsx'" },
          { type: "list", ordered: true, items: [
            "See the error in your browser",
            "Copy the entire error message",
            "Paste it back to Claude: 'I got this error, fix it'",
            "Watch Claude fix it",
          ] },
          { type: "callout", variant: "tip", text: "You just practiced the most important vibecoding skill: feeding errors to Claude. Remember this loop." },
        ],
      },
      {
        id: "push-to-github",
        title: "Step 7: Push to GitHub",
        content: [
          { type: "paragraph", text: "Tell Claude Code:" },
          { type: "code", code: "Initialise a git repo, commit everything, create a GitHub repo called my-site, and push", language: "prompt" },
          { type: "paragraph", text: "Claude handles all the git commands. Your code is now on GitHub." },
        ],
      },
      {
        id: "file-structure",
        title: "Step 8: Explore What Was Created",
        content: [
          { type: "command", command: "ls src/app/", description: "See the pages in your app" },
          { type: "command", command: "ls src/", description: "See the top-level source structure" },
          { type: "list", items: [
            "src/app/page.tsx — your homepage",
            "src/app/layout.tsx — the shell wrapping every page",
            "src/app/globals.css — your theme and styles",
            "package.json — your project's dependencies",
          ] },
          { type: "callout", variant: "meta", text: "Open src/app/page.tsx in this project. That's the file that renders the landing page you first saw. Every lesson uses the same pattern." },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────
  // LESSON 7: Deploying with Vercel
  // ──────────────────────────────────────────────
  {
    slug: "deploying-with-vercel",
    number: 7,
    title: "Deploying with Vercel",
    subtitle: "Put your site on the internet",
    estimatedMinutes: 10,
    sections: [
      {
        id: "deploy-walkthrough",
        title: "Deploy It",
        content: [
          { type: "paragraph", text: "Vercel takes your code from GitHub and makes it a live website. Every future push auto-redeploys." },
          { type: "list", ordered: true, items: [
            "Go to vercel.com (sign in with GitHub)",
            "Click 'New Project'",
            "Import your GitHub repo",
            "Click 'Deploy'",
            "Wait 30-60 seconds...",
          ] },
          { type: "callout", variant: "tip", title: "The Magic Moment", text: "Open the .vercel.app URL on your phone. Your site is on the internet. You built this." },
          { type: "callout", variant: "meta", text: "The URL you're reading this on IS a Vercel deployment. Same process, same tools." },
        ],
      },
      {
        id: "make-a-change",
        title: "Try It: Push an Update",
        content: [
          { type: "paragraph", text: "Now see continuous deployment in action:" },
          { type: "list", ordered: true, items: [
            "Ask Claude Code to change something on your site",
            "Tell Claude: 'commit and push'",
            "Watch Vercel auto-redeploy (check the Vercel dashboard)",
            "Refresh your live URL — the change is there",
          ] },
          { type: "paragraph", text: "That's the full loop: edit → push → live. Every time." },
        ],
      },
      {
        id: "good-to-know",
        title: "Good to Know (For Later)",
        content: [
          { type: "expandable", title: "Environment variables", content: [
            { type: "paragraph", text: "Vercel has a settings panel to store secrets (API keys, database passwords). Never put these in your code — anyone on GitHub can see them. You'll need this when you add databases or payments." },
          ]},
          { type: "expandable", title: "Custom domains", content: [
            { type: "paragraph", text: "Vercel gives you yourproject.vercel.app for free. You can connect a custom domain (yourname.com) in Vercel settings → Domains. Takes about 5 minutes." },
          ]},
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────
  // LESSON 8: The Debugging Mindset
  // ──────────────────────────────────────────────
  {
    slug: "the-debugging-mindset",
    number: 8,
    title: "The Debugging Mindset",
    subtitle: "Practice the skill that matters most",
    estimatedMinutes: 10,
    sections: [
      {
        id: "the-loop",
        title: "The Debugging Loop",
        content: [
          { type: "paragraph", text: "Errors are normal. Pros spend more time debugging than writing new code. Here's the process:" },
          { type: "list", ordered: true, items: [
            "See an error (in the browser or terminal)",
            "Copy the ENTIRE error message",
            "Paste it to Claude with context: 'I was trying to do X and got this error'",
            "Apply the fix",
            "Repeat until it works",
          ] },
          { type: "callout", variant: "tip", text: "Copy the ENTIRE error, not just the first line. The most useful info is often at the bottom." },
        ],
      },
      {
        id: "practice",
        title: "Try It: Break and Fix",
        content: [
          { type: "paragraph", text: "If you haven't already, let's practice:" },
          { type: "list", ordered: true, items: [
            "Right-click this page → Inspect → Console tab",
            "Note: no errors (this is a healthy page)",
            "Now in your project, ask Claude to 'add a component that imports something that doesn't exist'",
            "See the error → copy it → feed it back to Claude → fixed",
          ] },
        ],
      },
      {
        id: "when-stuck",
        title: "When You're Stuck",
        content: [
          { type: "list", items: [
            "Claude going in circles? Start a new conversation with a clearer prompt",
            "Stuck 15+ minutes? Describe the GOAL, not the error",
            "Google the error message — Stack Overflow often has the exact fix",
          ] },
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────
  // LESSON 9: What Comes Next
  // ──────────────────────────────────────────────
  {
    slug: "what-comes-next",
    number: 9,
    title: "What Comes Next",
    subtitle: "Where to go from here",
    estimatedMinutes: 5,
    sections: [
      {
        id: "advanced-features",
        title: "Things to Add Next",
        content: [
          { type: "list", items: [
            "Databases (Supabase, Vercel Postgres) — store and retrieve data",
            "Authentication (NextAuth, Clerk) — user sign-up and login",
            "Payments (Stripe) — charge money",
            "APIs — send emails, pull data, add AI features",
          ] },
          { type: "paragraph", text: "Each of these is one vibecoding session away." },
        ],
      },
      {
        id: "resources",
        title: "Resources",
        content: [
          { type: "list", items: [
            "Claude.ai — for any question, any time",
            "vercel.com/docs — excellent documentation",
            "nextjs.org/learn — free interactive tutorial",
          ] },
        ],
      },
      {
        id: "key-takeaway",
        title: "The Key Takeaway",
        content: [
          { type: "paragraph", text: "You need four skills:" },
          { type: "list", ordered: true, items: [
            "Describe what you want clearly",
            "Understand the system (frontend, backend, GitHub, Vercel)",
            "Debug fearlessly",
            "Ship fast and iterate",
          ] },
          { type: "callout", variant: "meta", text: "This website was built with exactly the process you just learned. Same tools, same prompts, same deploy. Now go build something of your own." },
        ],
      },
    ],
  },
];
